import Vue from "vue";
import Logo from './logo/logo';
import Icon from "./icon/icon";
import IconStore from "./icon/icon-store";
import darkLogo from './logo/dark-logo';
import imgLoading from './loading/img-loading';
import allDeveloper from './all-developer/all-developer';
import footerIcon from './footer-icon/footer-icon';
import dashboardButton from './dashboard-button/dashboard-button';
import titleName from './title-name/title-name.vue';
import lightpaper from "./lightpaper";
import bodyContent from './body-content';
Vue.component("a-logo", Logo);
Vue.component("a-dark-logo", darkLogo);
Vue.component("a-logo", Logo);
Vue.component("img-loading", imgLoading);
Vue.component('a-all-developer', allDeveloper);
Vue.component('a-footer-icon', footerIcon);
Vue.component('a-dashboard-button', dashboardButton);
Vue.component('a-title-name', titleName);
Vue.component('a-lightpaper', lightpaper);
Vue.component("a-icon", Icon);
Vue.component("a-icon-store", IconStore);
Vue.component("a-body-content", bodyContent);
